config/routes.rb
Rails.application.routes.draw do

  get '/' => "questions#index"

  resources :questions do
    resources :answers, only: [:index, :new, :create]
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  # GET /questions/:question_id/answers/new
  def new
    @question = Question.where(id: params[:question_id]).first
    @answer = Answer.new
  end

  # POST /questions/:question_id/answers
  def create
    @answer = Answer.create!(content: params[:answer][:content])
    @question = Question.where(id: params[:question_id]).first
    @question.answers << @answer

    redirect_to "/questions/#{@question.id}"
  end

  # POST /questions/:question_id/answers


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  # SHOW /questions/:id
  def show
    @question = Question.where(id: params[:id]).first
  end

  # GET /questions
  def index
    @questions = Question.all
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # POST /questions
  def create
    @question = Question.create!(
      title: params[:question][:title],
      content: params[:question][:content]
      )
    redirect_to "/questions/#{@question.id}"
  end

  # GET /questions/:question_id/edit
  def edit
    @question = Question.where(id: params[:id]).first
  end

  def update
    @question = Question.where(id: params[:id]).first
    @question.update(
      title: params[:question][:title],
      content: params[:question][:content]
      )
    redirect_to "/questions/#{@question.id}"
  end

  def destroy
    @question = Question.where(id: params[:id]).first
    @question.delete
    redirect_to "/questions"
  end
end


# test

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbcOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/edit.html.erb
<form action="/questions/<%= @question.id %>" method="post">
  <input name="_method" type="hidden" value="put" />
  <input type="text" placeholder="Title" name="question[title]" value="<%=@question.title %>">
  <input type="text" placeholder="Content" name="question[content]" value="<%=@question.content %>">
  <input type="submit" value="Update">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
</form>

app/views/questions/index.html.erb
<h1>All Questions</h1>

<% @questions.each do |q| %>
	<h2><%= q.title %> <a href="<%= question_path(q) %>">details</a></h2>
  <p><%= q.content %> </p>
<% end %>

<h1><a href="<%= new_question_path %>">Ask a Question</a></h1>

app/views/questions/new.html.erb
<form action="/questions" method="post">
  <input type="text" placeholder="Title" name="question[title]">
  <input type="text" placeholder="Content" name="question[content]">
  <input type="submit" value="Create">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
</form>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<a href="<%= edit_question_path(@question) %>">Edit Post</a>

<a href="/questions/<%= @question.id %>" data-method="delete">Delete Post</a>

<% if @question.answers.length == 0 %>
  <p>Be the first to post an answer!</p>
<% else %>
  <h3>Answers:</h3>
  <% @question.answers.each do |a| %>
    <p><%= a.content %></p>
  <% end %>
<% end %>

<h3>Post an Answer Here</h3>
<form action="/questions/<%= @question.id %>/answers" method="post">
  <input type="text" placeholder="Answer" name="answer[content]">
  <input type="submit" value="Post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
</form>

<a href="/questions">To All Questions</a>